<script setup lang="ts">
import type { components } from '~/api/schema'
import { unwrap,versionHeaders } from '~/api/client'
import { displayError } from '~/utils/errors'
import { formatDate,statusLabel } from '~/utils/format'
type Case=components['schemas']['OrderCase'];definePageMeta({middleware:['auth','admin']});const api=useMarketplaceApi();const cases=ref<Case[]>([]);const filter=ref('OPEN');const pending=ref(true);const message=ref('')
const shown=computed(()=>cases.value.filter(x=>!filter.value||x.state===filter.value));async function load(){pending.value=true;try{cases.value=unwrap(await api.GET('/admin/cases',{params:{query:{limit:100}},cache:'no-store'})).items}catch(cause){message.value=displayError(cause).message}finally{pending.value=false}}
async function resolve(item:Case){const reason=prompt('Tuliskan resolusi kasus minimal 3 karakter');if(!reason)return;try{unwrap(await api.POST('/admin/cases/{caseId}/resolve',{params:{path:{caseId:item.id},header:{...versionHeaders(item.row_version),'Idempotency-Key':crypto.randomUUID()}},body:{reason}}));await load()}catch(cause){message.value=displayError(cause).message}}
onMounted(()=>{void load()});useSeoMeta({title:'Manajemen kasus — Niaga'})
</script>
<template><main id="main-content" class="page-shell"><PortalNav area="admin"/><div class="section-heading"><div><p class="eyebrow">Trust & safety</p><h1>Kasus dan sengketa</h1></div><select v-model="filter" class="select-control"><option value="">Semua</option><option>OPEN</option><option>RESOLVED</option><option>REJECTED</option></select></div><p v-if="message" class="surface" role="status">{{message}}</p><ApiState :pending="pending" :empty="!pending&&!shown.length" empty-title="Tidak ada kasus pada filter ini"><div class="kanban-grid"><section v-for="state in ['OPEN','RESOLVED','REJECTED']" :key="state" class="kanban-column"><h2>{{statusLabel(state)}} · {{shown.filter(x=>x.state===state).length}}</h2><article v-for="item in shown.filter(x=>x.state===state)" :key="item.id" class="surface"><span class="badge">{{item.kind}}</span><h3>{{item.reason}}</h3><p class="muted">Order {{item.vendor_order_id.slice(0,8)}} · {{formatDate(item.created_at)}}</p><p v-if="item.resolution"><strong>Resolusi:</strong> {{item.resolution}}</p><button v-if="item.state==='OPEN'" @click="resolve(item)">Selesaikan kasus</button></article></section></div></ApiState></main></template>
