<script setup lang="ts">
import type{components}from'~/api/schema';import{unwrap,versionHeaders}from'~/api/client';import{displayError}from'~/utils/errors';import{formatDate,formatRupiah,statusLabel}from'~/utils/format';type Payout=components['schemas']['Payout'];definePageMeta({middleware:['auth','admin']});const api=useMarketplaceApi();const payout=ref<Payout>();const payoutId=ref('');const message=ref('');const createForm=reactive({store_id:'',bank_account_id:'',vendor_payable_id:'',amount:0});const result=reactive({state:'PAID' as 'PAID'|'FAILED'|'UNKNOWN',transfer_reference:'',proof_document_id:'',reason:''})
async function create(){try{payout.value=unwrap(await api.POST('/admin/payouts',{params:{header:{'Idempotency-Key':crypto.randomUUID()}},body:{store_id:createForm.store_id,bank_account_id:createForm.bank_account_id,lines:[{vendor_payable_id:createForm.vendor_payable_id,amount:createForm.amount}]}}));payoutId.value=payout.value.id}catch(cause){message.value=displayError(cause).message}}
async function load(){try{payout.value=unwrap(await api.GET('/admin/payouts/{payoutId}',{params:{path:{payoutId:payoutId.value}},cache:'no-store'}))}catch(cause){message.value=displayError(cause).message}}
async function transition(action:'approve'|'start'){if(!payout.value)return;const reason=prompt('Alasan tindakan minimal 3 karakter');if(!reason)return;try{payout.value=action==='approve'?unwrap(await api.POST('/admin/payouts/{payoutId}/approve',{params:{path:{payoutId:payout.value.id},header:{...versionHeaders(payout.value.row_version),'Idempotency-Key':crypto.randomUUID()}},body:{reason}})):unwrap(await api.POST('/admin/payouts/{payoutId}/start',{params:{path:{payoutId:payout.value.id},header:{...versionHeaders(payout.value.row_version),'Idempotency-Key':crypto.randomUUID()}},body:{reason}}))}catch(cause){message.value=displayError(cause).message}}
async function record(){if(!payout.value)return;try{payout.value=unwrap(await api.POST('/admin/payouts/{payoutId}/result',{params:{path:{payoutId:payout.value.id},header:{...versionHeaders(payout.value.row_version),'Idempotency-Key':crypto.randomUUID()}},body:{state:result.state,transfer_reference:result.transfer_reference||undefined,proof_document_id:result.proof_document_id||undefined,reason:result.reason}}))}catch(cause){message.value=displayError(cause).message}}
useSeoMeta({title:'Payout admin — Niaga'})
</script>
<template><main id="main-content" class="page-shell"><PortalNav area="admin"/><div class="section-heading"><div><p class="eyebrow">Dual control</p><h1>Payout vendor</h1></div></div><p v-if="message" class="surface" role="status">{{message}}</p><div class="admin-split"><form class="surface form-stack" @submit.prevent="create"><h2>Buat payout</h2><label class="form-field">Store ID<input v-model="createForm.store_id" required></label><label class="form-field">Bank account ID<input v-model="createForm.bank_account_id" required></label><label class="form-field">Payable ID<input v-model="createForm.vendor_payable_id" required></label><label class="form-field">Nominal<input v-model.number="createForm.amount" type="number" min="1" required></label><p class="form-help">Server memeriksa eligibility dan mengunci alokasi payable saat draft dibuat.</p><button>Buat draft</button></form><form class="surface form-stack" @submit.prevent="load"><h2>Muat payout</h2><label class="form-field">Payout ID<input v-model="payoutId" required></label><button class="button--secondary">Muat</button></form></div><section v-if="payout" class="surface section"><div class="section-heading"><div><h2>{{formatRupiah(payout.amount)}}</h2><p>{{formatDate(payout.created_at)}} · {{payout.id}}</p></div><span class="badge">{{statusLabel(payout.state)}}</span></div><p>Maker: {{payout.requested_by}}<br>Approver: {{payout.approved_by||'belum ada'}}</p><div class="form-actions"><button v-if="payout.state==='DRAFT'" @click="transition('approve')">Approve</button><button v-if="payout.state==='APPROVED'" @click="transition('start')">Mulai transfer manual</button></div><form v-if="['PROCESSING','UNKNOWN'].includes(payout.state)" class="form-stack section" @submit.prevent="record"><h3>Hasil transfer</h3><label class="form-field">Status<select v-model="result.state"><option>PAID</option><option>FAILED</option><option>UNKNOWN</option></select></label><label class="form-field">Referensi transfer<input v-model="result.transfer_reference"></label><label class="form-field">Proof document ID<input v-model="result.proof_document_id"></label><label class="form-field">Alasan<input v-model="result.reason" minlength="3" required></label><button>Rekam hasil</button></form></section></main></template>
