<script setup lang="ts">
import type { components } from '~/api/schema'
import { unwrap } from '~/api/client'
import { displayError } from '~/utils/errors'
import { formatRupiah, statusLabel } from '~/utils/format'
type Reconciliation=components['schemas']['Reconciliation']
definePageMeta({middleware:['auth','admin']});const api=useMarketplaceApi();const operationId=ref('');const reconciliationId=ref('');const record=ref<Reconciliation>();const message=ref('');const form=reactive({provider_account_id:'',period_start:new Date(Date.now()-86400000).toISOString().slice(0,16),period_end:new Date().toISOString().slice(0,16),source_document_id:''})
async function start(){try{const op=unwrap(await api.POST('/admin/reconciliations',{params:{header:{'Idempotency-Key':crypto.randomUUID()}},body:{provider_account_id:form.provider_account_id,period_start:new Date(form.period_start).toISOString(),period_end:new Date(form.period_end).toISOString(),source_document_id:form.source_document_id||undefined}}));operationId.value=op.id}catch(cause){message.value=displayError(cause).message}}
async function load(){try{record.value=unwrap(await api.GET('/admin/reconciliations/{reconciliationId}',{params:{path:{reconciliationId:reconciliationId.value}},cache:'no-store'}))}catch(cause){message.value=displayError(cause).message}}
useSeoMeta({title:'Rekonsiliasi pembayaran — Niaga'})
</script>
<template><main id="main-content" class="page-shell"><PortalNav area="admin"/><div class="section-heading"><div><p class="eyebrow">Settlement control</p><h1>Rekonsiliasi provider</h1></div></div><p v-if="message" class="surface" role="status">{{message}}</p><div class="admin-split"><form class="surface form-stack" @submit.prevent="start"><h2>Mulai run</h2><label class="form-field">Provider account ID<input v-model="form.provider_account_id" required></label><label class="form-field">Awal periode<input v-model="form.period_start" type="datetime-local" required></label><label class="form-field">Akhir periode<input v-model="form.period_end" type="datetime-local" required></label><label class="form-field">Source document ID<input v-model="form.source_document_id"></label><button>Jalankan rekonsiliasi</button><OperationStatus v-if="operationId" :operation-id="operationId"/></form><form class="surface form-stack" @submit.prevent="load"><h2>Muat hasil run</h2><label class="form-field">Reconciliation ID<input v-model="reconciliationId" required></label><button class="button--secondary">Muat rincian</button><template v-if="record"><span class="badge">{{statusLabel(record.state)}}</span><p>{{record.items.length}} mismatch ditemukan</p></template></form></div><section v-if="record" class="section"><h2>Mismatch</h2><div class="table-wrap surface"><table><thead><tr><th>Referensi eksternal</th><th>Jenis</th><th>Expected</th><th>Actual</th><th>Status</th></tr></thead><tbody><tr v-for="item in record.items" :key="item.external_reference"><td>{{item.external_reference}}</td><td>{{item.kind}}</td><td>{{item.expected_amount===undefined?'—':formatRupiah(item.expected_amount)}}</td><td>{{item.actual_amount===undefined?'—':formatRupiah(item.actual_amount)}}</td><td><span class="badge">{{statusLabel(item.state)}}</span></td></tr><tr v-if="!record.items.length"><td colspan="5">Tidak ada mismatch.</td></tr></tbody></table></div></section></main></template>
