<script setup lang="ts">
import { displayError } from '~/utils/errors';
const route = useRoute(); const email = ref(''); const password = ref(''); const showPassword = ref(false); const message = ref(''); const requestId = ref<string>();
const { login, pending } = useAuth();
function safeDestination(): string { const value = route.query.redirect; return typeof value === 'string' && value.startsWith('/') && !value.startsWith('//') ? value : '/'; }
async function submit() { message.value = ''; requestId.value = undefined; try { await login(email.value, password.value); await navigateTo(safeDestination()); } catch (error) { const shown = displayError(error, 'Tidak dapat terhubung ke layanan masuk.'); message.value = shown.message; requestId.value = shown.requestId; } }
useSeoMeta({ title: 'Masuk — Niaga' });
</script>
<template><main id="main-content" class="auth-shell"><form class="auth-card" novalidate @submit.prevent="submit"><p class="eyebrow">Akun Niaga</p><h1>Selamat datang kembali</h1><p class="muted">Masuk untuk melanjutkan belanja dan mengelola transaksi.</p><label class="form-field">Email<input v-model.trim="email" required type="email" autocomplete="email" placeholder="nama@email.com"></label><label class="form-field">Password<div class="input-action"><input v-model="password" required :type="showPassword ? 'text' : 'password'" minlength="12" autocomplete="current-password"><button type="button" :aria-pressed="showPassword" @click="showPassword = !showPassword">{{ showPassword ? 'Sembunyi' : 'Lihat' }}</button></div></label><div v-if="message" class="error" role="alert"><strong>{{ message }}</strong><small v-if="requestId"><br>ID permintaan: {{ requestId }}</small></div><button :disabled="pending || !email || password.length < 12" type="submit">{{ pending ? 'Memproses…' : 'Masuk' }}</button><div class="auth-links"><NuxtLink to="/lupa-password">Lupa password?</NuxtLink><NuxtLink to="/register">Belum punya akun? Daftar</NuxtLink></div></form></main></template>
