<script setup lang="ts">
import { unwrap } from '~/api/client'
import { displayError } from '~/utils/errors'
import { formatDate } from '~/utils/format'
const api=useMarketplaceApi();const state=ref<'checking'|'operational'|'degraded'>('checking');const checkedAt=ref('');const latency=ref(0);const message=ref('')
async function check(){state.value='checking';message.value='';const started=performance.now();try{unwrap(await api.GET('/categories',{params:{query:{limit:1}},cache:'no-store'}));latency.value=Math.round(performance.now()-started);state.value='operational'}catch(cause){state.value='degraded';message.value=displayError(cause).message}finally{checkedAt.value=new Date().toISOString()}}
onMounted(()=>{void check()});useSeoMeta({title:'Status layanan — Niaga',description:'Status ketersediaan layanan marketplace Niaga.'})
</script>
<template><main id="main-content" class="page-shell status-page"><section class="status-hero" :class="`status-hero--${state}`"><span class="status-dot"/><div><p class="eyebrow">Service health</p><h1>{{state==='checking'?'Memeriksa layanan…':state==='operational'?'Semua sistem beroperasi':'Layanan mengalami gangguan'}}</h1><p v-if="checkedAt">Pemeriksaan terakhir {{formatDate(checkedAt)}} · {{latency}} ms</p></div><button class="button--secondary" :disabled="state==='checking'" @click="check">Periksa lagi</button></section><section class="section"><h2>Komponen layanan</h2><div class="metric-grid"><article v-for="component in ['Web storefront','Marketplace API','Autentikasi','Checkout & order']" :key="component" class="surface metric"><span>{{component}}</span><strong>{{state==='operational'?'Operasional':state==='checking'?'Memeriksa':'Terganggu'}}</strong></article></div><p v-if="message" class="error surface">{{message}}</p></section><section class="surface section"><div class="section-heading"><h2>Riwayat insiden</h2><span class="badge">30 hari</span></div><div class="incident-empty"><span aria-hidden="true">✓</span><div><strong>Tidak ada insiden yang tercatat</strong><p class="muted">Status ini mengukur koneksi storefront ke API secara langsung.</p></div></div></section></main></template>
