<script setup lang="ts">
import type { components } from '~/api/schema'; import { unwrap, versionHeaders } from '~/api/client'; import { displayError } from '~/utils/errors'; import { formatRupiah, statusLabel } from '~/utils/format';
type Attempt = components['schemas']['PaymentAttempt']; type Operation = components['schemas']['AsyncOperation'];
definePageMeta({ middleware: 'auth' }); const api = useMarketplaceApi(); const route = useRoute(); const cartApi = useCart(); const attempt = ref<Attempt>(); const operation = ref<Operation>(); const pending = ref(true); const error = ref<unknown>(); const copied = ref(false); let poll: ReturnType<typeof setInterval>|undefined;
const secondsLeft = ref(0); const terminal = computed(() => attempt.value?.state === 'TERMINAL'); const underReview = computed(() => attempt.value?.state === 'UNKNOWN' || operation.value?.state === 'REVIEW');
async function load() { try { if (!cartApi.account.value) await cartApi.load(); const operationId = typeof route.query.operation_id === 'string' ? route.query.operation_id : ''; const [attemptResult, operationResult] = await Promise.all([api.GET('/buyer-accounts/{buyerAccountId}/payment-attempts/{paymentAttemptId}', { params: { path: { buyerAccountId: cartApi.account.value!.id, paymentAttemptId: String(route.params.id) } }, cache: 'no-store' }), operationId ? api.GET('/operations/{operationId}', { params: { path: { operationId } }, cache: 'no-store' }) : Promise.resolve(undefined)]); attempt.value = unwrap(attemptResult); operation.value = operationResult ? unwrap(operationResult) : undefined; secondsLeft.value = attempt.value.expires_at ? Math.max(0, Math.floor((new Date(attempt.value.expires_at).getTime()-Date.now())/1000)) : 0; if (terminal.value || underReview.value || secondsLeft.value === 0 && attempt.value.expires_at) clearInterval(poll); } catch (cause) { error.value = cause; clearInterval(poll); } finally { pending.value = false; } }
async function copyReference() { const value = attempt.value?.redirect_url || attempt.value?.snap_token || attempt.value?.id; if (!value) return; await navigator.clipboard.writeText(value); copied.value = true; setTimeout(() => { copied.value = false; }, 1800); }
async function cancelAttempt() { if (!attempt.value || !cartApi.account.value || !confirm('Tutup upaya pembayaran ini? Gunakan hanya bila Anda ingin mengganti metode.')) return; try { unwrap(await api.POST('/buyer-accounts/{buyerAccountId}/payment-attempts/{paymentAttemptId}/cancel', { params: { path: { buyerAccountId: cartApi.account.value.id, paymentAttemptId: attempt.value.id }, header: { ...versionHeaders(attempt.value.row_version), 'Idempotency-Key': crypto.randomUUID() } }, body: { reason: 'Pengguna meminta pergantian metode pembayaran.' } })); await load(); } catch (cause) { error.value = cause; } }
onMounted(() => { void load(); poll = setInterval(() => { if (secondsLeft.value > 0) secondsLeft.value--; void load(); }, 3000); }); onUnmounted(() => clearInterval(poll));
useSeoMeta({ title: 'Sesi pembayaran — Niaga' });
</script>
<template><main id="main-content" class="auth-shell"><ApiState :pending="pending" :error="error ? displayError(error) : null" @retry="load"><section v-if="attempt" class="auth-card payment-card"><p class="eyebrow">Sesi pembayaran</p><div class="section-heading"><h1>{{ underReview ? 'Dalam pemeriksaan' : terminal ? 'Status final' : 'Selesaikan pembayaran' }}</h1><span class="badge" :class="{ 'badge--warning': !terminal }">{{ statusLabel(attempt.provider_status || attempt.state) }}</span></div><p v-if="attempt.expires_at && !terminal" class="countdown" aria-live="polite">Sisa waktu {{ Math.floor(secondsLeft/60).toString().padStart(2,'0') }}:{{ (secondsLeft%60).toString().padStart(2,'0') }}</p><div class="surface"><div class="summary-line"><span>Nominal</span><strong>{{ formatRupiah(attempt.amount) }}</strong></div><div class="summary-line"><span>Metode</span><strong>{{ attempt.channel?.toUpperCase() || 'Otomatis' }}</strong></div><div class="summary-line"><span>Referensi</span><code>{{ attempt.id }}</code></div></div><p v-if="underReview" class="success">Status provider belum pasti. Jangan membuat pembayaran kedua sampai pemeriksaan selesai.</p><p v-else-if="attempt.state === 'CREATING'">Provider sedang menyiapkan instruksi pembayaran. Halaman diperbarui otomatis.</p><template v-else-if="!terminal"><a v-if="attempt.redirect_url" class="button" :href="attempt.redirect_url" rel="noopener noreferrer">Buka halaman pembayaran</a><button v-if="attempt.snap_token || attempt.redirect_url" class="button--secondary" type="button" @click="copyReference">{{ copied ? 'Tersalin' : 'Salin referensi' }}</button><button class="text-button" type="button" @click="cancelAttempt">Ganti metode pembayaran</button></template><NuxtLink v-if="typeof route.query.order_id === 'string'" class="button button--secondary" :to="`/akun/pesanan/${route.query.order_id}`">Kembali ke detail pesanan</NuxtLink><small class="muted">Status browser tidak mengubah transaksi. Niaga hanya menandai lunas setelah settlement terverifikasi backend.</small></section></ApiState></main></template>
