<script setup lang="ts">
import type { components } from '~/api/schema'
import { errorFromResponse } from '~/api/client'
const props = defineProps<{ legalEntityId?: string; vendorOrderId?: string; allowedTypes?: string[] }>()
const emit = defineEmits<{ uploaded: [document: components['schemas']['Document']] }>()
const api=useMarketplaceApi();const config=useRuntimeConfig();const file=ref<File>();const fileInput=ref<HTMLInputElement>();const documentType=ref(props.allowedTypes?.[0]??'OTHER');const pending=ref(false);const message=ref('');const dragging=ref(false)
const types=computed(()=>props.allowedTypes??(props.legalEntityId?['NPWP','PKP','SKB','TURNOVER_STATEMENT','OTHER']:['INVOICE','TAX_INVOICE','OTHER']))
function validate(selected?:File){message.value='';if(!selected){file.value=undefined;return}if(!['application/pdf','image/jpeg','image/png'].includes(selected.type)){message.value=`${selected.name}: format harus PDF, JPG, atau PNG.`;file.value=undefined;return}if(selected.size>10*1024*1024){message.value=`${selected.name}: file maksimal 10 MB.`;file.value=undefined;return}file.value=selected}
function pick(event:Event){validate((event.target as HTMLInputElement).files?.[0])}function drop(event:DragEvent){dragging.value=false;validate(event.dataTransfer?.files?.[0])}
async function upload(){if(!file.value||(!props.legalEntityId&&!props.vendorOrderId))return;pending.value=true;message.value='';try{const body=new FormData();body.append('file',file.value);body.append('document_type',documentType.value);if(props.legalEntityId)body.append('legal_entity_id',props.legalEntityId);else body.append('vendor_order_id',props.vendorOrderId!);const response=await fetch(`${String(config.public.apiBase).replace(/\/$/,'')}/documents`,{method:'POST',credentials:'include',headers:{'X-CSRF-Token':await api.refreshCsrf(),'Idempotency-Key':crypto.randomUUID()},body});const data=await response.json();if(!response.ok)throw errorFromResponse(response,data);emit('uploaded',data);file.value=undefined;message.value='Dokumen berhasil diunggah dan menunggu verifikasi.'}catch(cause){message.value=cause instanceof Error?cause.message:'Upload gagal.'}finally{pending.value=false}}
</script>
<template><form class="upload-box" @submit.prevent="upload"><label class="form-field">Tipe dokumen<select v-model="documentType"><option v-for="type in types" :key="type" :value="type">{{type}}</option></select></label><label class="media-dropzone media-dropzone--document" :class="{dragging}" tabindex="0" @dragover.prevent="dragging=true" @dragleave.prevent="dragging=false" @drop.prevent="drop" @keydown.enter.prevent="fileInput?.click()"><input ref="fileInput" class="sr-only" type="file" accept="application/pdf,image/jpeg,image/png" @change="pick"><strong>{{file?.name||'Tarik dokumen atau tekan Enter untuk memilih'}}</strong><small>PDF, JPG, atau PNG · maksimal 10 MB</small></label><button :disabled="pending||!file">{{pending?'Mengunggah…':'Unggah dokumen'}}</button><small v-if="file">{{Math.ceil(file.size/1024)}} KB</small><p v-if="message" role="status">{{message}}</p></form></template>
