<script setup lang="ts">
import type { components } from '~/api/schema';
import { unwrap } from '~/api/client'; import { displayError } from '~/utils/errors';
type OrganizationCreate = components['schemas']['OrganizationCreate'];
definePageMeta({ middleware: 'auth' }); const api = useMarketplaceApi(); const cartApi = useCart();
const form = reactive<OrganizationCreate>({ name: '', kind: 'COMPANY', contact_name: '', contact_phone: '' });
const showForm = ref(false); const pending = ref(false); const message = ref('');
onMounted(() => { void cartApi.loadAccounts().catch(cause => { message.value = displayError(cause).message; }); });
async function create() { pending.value = true; message.value = ''; try { const created = unwrap(await api.POST('/me/organizations', { params: { header: { 'Idempotency-Key': crypto.randomUUID() } }, body: { ...form, school_identifier: form.school_identifier || undefined } })); await cartApi.loadAccounts(); await cartApi.selectAccount(created.id); showForm.value = false; message.value = 'Organisasi dibuat dan dipilih sebagai konteks pembelian.'; } catch (cause) { message.value = displayError(cause).message; } finally { pending.value = false; } }
async function choose(id: string) { pending.value = true; try { await cartApi.selectAccount(id); message.value = 'Konteks pembelian diperbarui.'; } catch (cause) { message.value = displayError(cause).message; } finally { pending.value = false; } }
useSeoMeta({ title: 'Organisasi — Niaga' });
</script>

<template><main id="main-content" class="page-shell"><BuyerNav/><div class="section-heading"><div><p class="eyebrow">Konteks pembelian</p><h1>Pribadi dan organisasi</h1></div><button type="button" @click="showForm=!showForm">{{ showForm ? 'Tutup' : 'Tambah organisasi' }}</button></div><p v-if="message" class="success" role="status">{{ message }}</p><form v-if="showForm" class="surface address-form" @submit.prevent="create"><h2 class="form-span">Organisasi baru</h2><label class="form-field">Nama<input v-model.trim="form.name" required maxlength="200"></label><label class="form-field">Jenis<select v-model="form.kind"><option value="SCHOOL">Sekolah</option><option value="COMPANY">Perusahaan</option><option value="OTHER">Lainnya</option></select></label><label class="form-field">Kontak<input v-model.trim="form.contact_name" required maxlength="200"></label><label class="form-field">Telepon<input v-model.trim="form.contact_phone" required maxlength="32"></label><label v-if="form.kind==='SCHOOL'" class="form-field">ID sekolah<input v-model.trim="form.school_identifier" maxlength="200"></label><button :disabled="pending" type="submit">{{ pending ? 'Menyimpan…' : 'Buat organisasi' }}</button></form><div class="address-grid"><article v-for="item in cartApi.accounts.value" :key="item.id" class="surface address-card"><div class="section-heading"><h2>{{ item.kind === 'INDIVIDUAL' ? 'Pribadi' : item.organization_name }}</h2><span v-if="item.id===cartApi.account.value?.id" class="badge">Aktif</span></div><p class="muted">{{ item.kind === 'INDIVIDUAL' ? 'Pembelian atas nama pribadi' : 'Dikelola satu manager pada MVP' }}</p><button v-if="item.id!==cartApi.account.value?.id" class="button--secondary" :disabled="pending" @click="choose(item.id)">Gunakan konteks</button></article></div></main></template>
