<script setup lang="ts">
import type { components } from '~/api/schema'; import { unwrap, versionHeaders } from '~/api/client'; import { displayError } from '~/utils/errors'; import { formatDate, formatRupiah, statusLabel } from '~/utils/format';
type Quote = components['schemas']['QuoteRequest']; type Version = components['schemas']['QuoteVersion']; definePageMeta({ middleware: 'auth' }); const api = useMarketplaceApi(); const route = useRoute(); const cartApi = useCart(); const quote = ref<Quote>(); const storeName = ref(''); const pending = ref(true); const actionPending = ref(false); const error = ref<unknown>(); const message = ref('');
const latestOffer = computed(() => [...(quote.value?.versions ?? [])].reverse().find(v => v.status === 'OFFERED'));
async function load() { pending.value = true; error.value = undefined; try { if (!cartApi.account.value) await cartApi.load(); quote.value = unwrap(await api.GET('/buyer-accounts/{buyerAccountId}/quote-requests/{quoteRequestId}', { params: { path: { buyerAccountId: cartApi.account.value!.id, quoteRequestId: String(route.params.id) } }, cache: 'no-store' })); try { storeName.value = unwrap(await api.GET('/stores/{storeId}', { params: { path: { storeId: quote.value.store_id } } })).name; } catch { storeName.value = `Toko ${quote.value.store_id.slice(0,8)}`; } } catch (cause) { error.value = cause; } finally { pending.value = false; } }
async function decide(version: Version, action:'accept'|'decline') { if (!cartApi.account.value) return; actionPending.value = true; message.value = ''; try { const params = { path: { buyerAccountId: cartApi.account.value.id, quoteVersionId: version.id }, header: { ...versionHeaders(version.row_version), 'Idempotency-Key': crypto.randomUUID() } }; if (action === 'accept') { unwrap(await api.POST('/buyer-accounts/{buyerAccountId}/quote-versions/{quoteVersionId}/accept', { params })); await cartApi.load(); message.value = 'Penawaran diterima dan seluruh item dimasukkan ke keranjang.'; } else { unwrap(await api.POST('/buyer-accounts/{buyerAccountId}/quote-versions/{quoteVersionId}/decline', { params })); message.value = 'Penawaran ditolak.'; } await load(); } catch (cause) { message.value = displayError(cause).message; } finally { actionPending.value = false; } }
onMounted(() => { void load(); }); useSeoMeta({ title: 'Detail RFQ — Niaga' });
</script>
<template><main id="main-content" class="page-shell"><BuyerNav/><ApiState :pending="pending" :error="error ? displayError(error) : null" @retry="load"><template v-if="quote"><div class="section-heading"><div><p class="eyebrow">RFQ {{ quote.id.slice(0,8) }}</p><h1>{{ storeName }}</h1><p class="muted">Dibuat {{ formatDate(quote.created_at) }}</p></div><span class="badge badge--warning">{{ statusLabel(quote.status) }}</span></div><p v-if="message" class="success" role="status">{{ message }}</p><div class="order-detail-grid"><section class="checkout-steps"><article class="surface"><h2>Kebutuhan awal</h2><div v-for="item in quote.items" :key="item.sku_id" class="summary-line"><span><strong>{{ item.product_name }}</strong><small class="muted"> · {{ item.sku_code }}</small></span><strong>{{ item.quantity }} unit</strong></div></article><article v-for="version in [...quote.versions].reverse()" :key="version.id" class="surface"><div class="section-heading"><h2>Versi {{ version.version_no }}</h2><span class="badge" :class="{ 'badge--warning': version.status === 'OFFERED' }">{{ statusLabel(version.status) }}</span></div><p>Berlaku sampai {{ formatDate(version.expires_at) }}</p><div v-for="item in version.items" :key="item.id" class="summary-line"><span>{{ item.product_name }} · {{ item.quantity }} × {{ formatRupiah(item.unit_price_gross) }}</span><strong>{{ formatRupiah(item.quantity * item.unit_price_gross) }}</strong></div><strong>Total {{ formatRupiah(version.items.reduce((sum,item)=>sum+item.quantity*item.unit_price_gross,0)) }}</strong></article></section><aside class="surface order-summary"><h2>Tindakan</h2><template v-if="latestOffer"><p>Periksa jumlah, harga, dan masa berlaku sebelum menerima seluruh versi.</p><button :disabled="actionPending" @click="decide(latestOffer,'accept')">Terima seluruh penawaran</button><button class="button--secondary" :disabled="actionPending" @click="decide(latestOffer,'decline')">Tolak penawaran</button></template><p v-else class="muted">Belum ada penawaran aktif dari vendor.</p><NuxtLink v-if="quote.versions.some(v=>v.status==='ACCEPTED')" class="button" to="/akun/keranjang">Lihat keranjang</NuxtLink></aside></div></template></ApiState></main></template>
