<script setup lang="ts">
import type { components } from '~/api/schema'; import { unwrap } from '~/api/client'; import { displayError } from '~/utils/errors'; import { formatRupiah, variantLabel } from '~/utils/format';
type SkuChoice = components['schemas']['Sku'] & { product_name: string }; type Line = { sku_id: string; quantity: number };
definePageMeta({ middleware: 'auth' }); const api = useMarketplaceApi(); const route = useRoute(); const cartApi = useCart(); const addressApi = useAddresses(); const storeId = ref(typeof route.query.store_id === 'string' ? route.query.store_id : ''); const storeName = ref(''); const choices = ref<SkuChoice[]>([]); const addressId = ref(''); const notes = ref(''); const lines = reactive<Line[]>([{ sku_id: typeof route.query.sku_id === 'string' ? route.query.sku_id : '', quantity: 1 }]); const pending = ref(true); const saving = ref(false); const error = ref<unknown>(); const message = ref('');
async function load() { pending.value = true; try { if (!storeId.value) throw new Error('Pilih produk dari katalog untuk menentukan vendor RFQ.'); await Promise.all([cartApi.load(),addressApi.load()]); const [store,products] = await Promise.all([api.GET('/stores/{storeId}', { params: { path: { storeId: storeId.value } } }).then(unwrap),api.GET('/products', { params: { query: { store_id: storeId.value, limit: 100 } } }).then(unwrap)]); storeName.value = store.name; choices.value = products.items.flatMap(product => product.skus.filter(sku => sku.status === 'ACTIVE').map(sku => ({ ...sku, product_name: product.name }))); addressId.value = addressApi.addresses.value.find(a=>a.is_default)?.id ?? addressApi.addresses.value[0]?.id ?? ''; } catch (cause) { error.value = cause; } finally { pending.value = false; } }
function addLine() { lines.push({ sku_id: '', quantity: 1 }); } function removeLine(index:number) { if (lines.length > 1) lines.splice(index,1); }
async function submit() { if (!cartApi.account.value || !storeId.value) return; message.value = ''; if (!addressId.value) { message.value = 'Pilih atau tambahkan alamat tujuan.'; return; } if (new Set(lines.map(x=>x.sku_id)).size !== lines.length || lines.some(x=>!x.sku_id || x.quantity < 1)) { message.value = 'Setiap SKU harus unik dengan jumlah positif.'; return; } saving.value = true; try { const quote = unwrap(await api.POST('/buyer-accounts/{buyerAccountId}/quote-requests', { params: { path: { buyerAccountId: cartApi.account.value.id }, header: { 'Idempotency-Key': crypto.randomUUID() } }, body: { store_id: storeId.value, address_id: addressId.value, notes: notes.value || undefined, items: lines } })); await navigateTo(`/akun/rfq/${quote.id}`); } catch (cause) { message.value = displayError(cause).message; } finally { saving.value = false; } }
onMounted(() => { void load(); }); useSeoMeta({ title: 'Buat RFQ — Niaga' });
</script>
<template><main id="main-content" class="page-shell"><BuyerNav/><ApiState :pending="pending" :error="error ? displayError(error) : null" @retry="load"><form class="surface rfq-form" @submit.prevent="submit"><p class="eyebrow">Penawaran satu vendor</p><h1>Minta penawaran</h1><p><strong>{{ storeName }}</strong></p><label class="form-field">Alamat tujuan<select v-model="addressId" required><option value="">Pilih alamat</option><option v-for="address in addressApi.addresses.value" :key="address.id" :value="address.id">{{ address.label }} — {{ address.city }}</option></select></label><NuxtLink v-if="!addressApi.addresses.value.length" to="/akun/alamat">Tambah alamat dahulu</NuxtLink><fieldset><legend>Produk dan jumlah</legend><div v-for="(line,index) in lines" :key="index" class="rfq-line"><label class="form-field">SKU<select v-model="line.sku_id" required><option value="">Pilih produk</option><option v-for="choice in choices" :key="choice.id" :value="choice.id">{{ choice.product_name }} · {{ variantLabel(choice.variant_attributes) || choice.sku_code }} · {{ formatRupiah(choice.unit_price_gross) }}</option></select></label><label class="form-field">Jumlah<input v-model.number="line.quantity" type="number" min="1" step="1" required></label><button class="text-button" type="button" @click="removeLine(index)">Hapus</button></div><button class="button--secondary" type="button" :disabled="lines.length >= 100" @click="addLine">Tambah baris</button></fieldset><label class="form-field">Catatan<textarea v-model.trim="notes" maxlength="2000" rows="5" placeholder="Spesifikasi atau kebutuhan khusus (opsional)"/></label><small class="muted">Harga RFQ belum mereservasi stok.</small><p v-if="message" class="error" role="alert">{{ message }}</p><button :disabled="saving || !addressId || !choices.length" type="submit">{{ saving ? 'Mengirim…' : 'Kirim RFQ' }}</button></form></ApiState></main></template>
